// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GenericDataServiceClient is the client API for GenericDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GenericDataServiceClient interface {
	Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Data, error)
	Set(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Response, error)
	Delete(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Response, error)
}

type genericDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGenericDataServiceClient(cc grpc.ClientConnInterface) GenericDataServiceClient {
	return &genericDataServiceClient{cc}
}

func (c *genericDataServiceClient) Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Data, error) {
	out := new(Data)
	err := c.cc.Invoke(ctx, "/GenericDataService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *genericDataServiceClient) Set(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/GenericDataService/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *genericDataServiceClient) Delete(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/GenericDataService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GenericDataServiceServer is the server API for GenericDataService service.
// All implementations must embed UnimplementedGenericDataServiceServer
// for forward compatibility
type GenericDataServiceServer interface {
	Get(context.Context, *Key) (*Data, error)
	Set(context.Context, *Data) (*Response, error)
	Delete(context.Context, *Key) (*Response, error)
	mustEmbedUnimplementedGenericDataServiceServer()
}

// UnimplementedGenericDataServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGenericDataServiceServer struct {
}

func (UnimplementedGenericDataServiceServer) Get(context.Context, *Key) (*Data, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedGenericDataServiceServer) Set(context.Context, *Data) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedGenericDataServiceServer) Delete(context.Context, *Key) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedGenericDataServiceServer) mustEmbedUnimplementedGenericDataServiceServer() {}

// UnsafeGenericDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GenericDataServiceServer will
// result in compilation errors.
type UnsafeGenericDataServiceServer interface {
	mustEmbedUnimplementedGenericDataServiceServer()
}

func RegisterGenericDataServiceServer(s grpc.ServiceRegistrar, srv GenericDataServiceServer) {
	s.RegisterService(&GenericDataService_ServiceDesc, srv)
}

func _GenericDataService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenericDataServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GenericDataService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenericDataServiceServer).Get(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _GenericDataService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenericDataServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GenericDataService/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenericDataServiceServer).Set(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

func _GenericDataService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenericDataServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GenericDataService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenericDataServiceServer).Delete(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

// GenericDataService_ServiceDesc is the grpc.ServiceDesc for GenericDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GenericDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GenericDataService",
	HandlerType: (*GenericDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _GenericDataService_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _GenericDataService_Set_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _GenericDataService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc.proto",
}
